---
title: Project Review - Part 5
author: Austin Thrash - FFK221
date: today
format: 
  html:
    toc: true
    toc-depth: 3
    number-sections: true
---

# Overview

Title of project: What Can Predict a Game's Userscore?

Name of project author(s): Aiden Sutherland

Name of project reviewer: Austin Thrash

# Instructions

Write your comments and feedback below for each section/component of the project. The goal should be to help the author improve their project. Make comments as constructive and actionable as possible. You can provide both criticism and praise.

For each component, pick one summary statement by deleting the ones that do not apply and keeping only the one that you think most closely summarizes a given component.

Make sure your final document compiles/renders into a readable, well-formatted html document.

Delete any sections/text of this template that are not part of your final review document. (Including these instructions.)

# Specific project content evaluation

Evaluate the different parts of the project by filling in the sections below.

## Background, Context and Motivation

How well is the context of the project described? Is a comprehensive background, including summary of previous/related work given? Is the project well placed into the context of existing work (including proper referencing of existing work). Is it clear why the project was undertaken and what new information it hopes to provide?

### Feedback and Comments

I believe the context and motivation behind the project is described well. The author has a personal connection to the subject as well since they are a video game consumer themselves. I do think that adding more examples of prior research would add further validity to the overall project and might help place it into the context of existing research. I can certainly see why this topic was picked for an analysis project as I too find it interesting.

### Summary assessment (PICK ONE, DELETE THE OTHERS)

-   strong contextualization and motivation

## Question description

How well and clear are the question(s)/hypotheses the project aims to address described? Is it clear how the questions relate to the data?

### Feedback and Comments

I think the background and summary do a great job at setting up the question/hypothesis. I had no issues understanding the goal of the project and the new information it is hoping to obtain.

### Summary assessment

-   question/hypotheses fully clear

## Data description

How well is the data overall described? Is the source provided? Is a codebook or other meta-information available that makes it clear what the data is?

### Feedback and Comments

While the author does a good job of describing where the data comes from, I feel as if it may be helpful to also include a table listing and describing each feature/variable; 13 variables are mentioned but never described so adding this might add clarity to the data description section.

### Summary assessment

-   source and overall structure of data somewhat explained

## Data wrangling and exploratory analysis

How well is the data cleaned/processed and explored? Are all steps reasonable and well explained? Are alternatives discussed and considered? Are meaningful exploratory results shown (e.g. in the supplementary materials)?

### Feedback and Comments

Like previously mentioned, 13 variables are mentioned but are not fully explored. These variables are explored further in the eda files for this project, however I think the manuscript would benefit from having more exploratory analysis information.

### Summary assessment

-   some weaknesses in wrangling and exploratory component (mainly in manuscript)

## Appropriateness of Analysis

Were the analysis methods appropriate for the data? Was the analysis done properly? Were different components of the analysis (e.g. performance measure, variable selection, data pre-processing, model evaluation) done in the best way possible and explained well?

### Feedback and Comments

Both random forest and linear regression are appropriate for this type of analysis. However, one suggestion might be to include why these models are appropriate for this study, including this will add more validity to the authors model selection.

### Summary assessment

-   strong and reasonable analysis

## Presentation

How well are results presented? Are tables and figures easy to read and understand? Are the main figures/tables publication level quality?

### Feedback and Comments

The results are presented nicely showing display "Actual vs. Prediction" for each model. One suggestion might be to have a plot that visually compares the performance of the two models, by whatever metric seems appropriate(RSME, R-Squared, etc...).

### Summary assessment

-   results are very well presented

## Discussion/Conclusions

Are the study findings properly discussed? Are strengths and limitations acknowledged? Are findings interpreted properly?

### Feedback and Comments

The findings of the study where properly discussed and the strengths and limitations were acknowledged. The results were explained thoroughly and the study had a satisfying conclusion.

### Summary assessment

-   strong, complete and clear discussion

## Further comments

*Add any other comments regarding the different aspects of the project here. Write anything you think can help your classmate improve their project.*

I really liked this project and thought my classmate did a wonderful job, I really liked the topic selection as well. I also thought it was cool how they exported the manuscript as a docx file which made it easier to view and read through.

# Overall project content evaluation

Evaluate overall features of the project by filling in the sections below.

## Structure

Is the project well structured? Are files in well labeled folders? Do files have reasonable names? Are all "junk" files not needed for analysis/reproduction removed? By just looking at files and folders, can you get an idea of how things fit together?

### Feedback and Comments

I was very impressed by how well the project is structured and how nicely everything is organized. From my knowledge there do not seem to be any "junk" files or folders in the project; everything included is used in the project.

### Summary assessment

-   well structured

## Documentation

How well is the project documented? Are you able to understand each step of the whole analysis, each decision that was made, and each line of code? Is enough information provided as comments in code or as part of Rmd files?

### Feedback and Comments

All readme files were cleanly documented explaining the process one needs to undertake to reproduce the project. All code was define by either comments or via summaries before the code block. Very clean and easy to follow!

### Summary assessment

-   fully and well documented

## Reproducibility

Are all results fully reproducible? Is documentation provided which clearly explains how to reproduce things, and does it work without the need for any manual intervention? Are you able to re-run the whole analysis without having to do manual interventions/edits?

### Feedback and Comments

The only issue I have found when attempting to reproduce the document is loading the data. Some of the data loading is directly referencing the github rather than the file location in the project so it is causing issues loading the data properly. Other than that, everything else appear reproducible.

### Summary assessment

-   small parts not reproducible or required manual intervention

## Thoroughness

How thorough was the overall study? Were alternatives (e.g. different ways of processing the data or different models) considered? Were alternatives discussed? Were the questions/hypotheses fully and thoroughly addressed?

### Feedback and Comments

While I believe my classmate did a really good job overall, I still think they could look at some alternative models or model parameters and make the project even more interesting. Fine tuning the models or using a including a few more may provide better detail on the accuracy of all the models as you have more data to compare to.

### Summary assessment

-   decent level of thoroughness

## Further comments

*Add any other comments regarding the overall project here. Write anything you think can help your classmate improve their project.*

They did a fantastic job overall! Very interesting topic too!
